name: Release Lock Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "lock or unlock"
        required: true
        type: choice
        options:
          - lock
          - unlock

permissions:
  contents: write

jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Lock
        if: inputs.action == 'lock'
        run: |
          git checkout -b release-lock
          git push origin release-lock
          echo "リリースロックを有効にしました。"

      - name: Unlock
        if: inputs.action == 'unlock'
        run: |
          git push origin --delete release-lock
          echo "リリースロックを解除しました。"
